<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="2" failures="1" disabled="0" errors="0" timestamp="2013-08-27T22:21:59" time="0" name="AllTests">
  <testsuite name="FooTest" tests="1" failures="0" disabled="0" errors="0" time="0">
    <testcase name="HandleNoneZeroInput" status="run" time="0" classname="FooTest" />
  </testsuite>
  <testsuite name="AddTest" tests="1" failures="1" disabled="0" errors="0" time="0">
    <testcase name="NormalInput" status="run" time="0" classname="AddTest">
      <failure message="test.cpp:25&#x0A;Value of: add(1, 4)&#x0A;  Actual: 5&#x0A;Expected: 2" type=""><![CDATA[test.cpp:25
Value of: add(1, 4)
  Actual: 5
Expected: 2]]></failure>
    </testcase>
  </testsuite>
</testsuites>
